preserve_hierarchy: true
files:
  - source: /origin/*.csv
    translation: /%osx_locale%/%original_file_name%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,source_phrase,context,de,es-ES,nl'
